# -*- coding: utf-8 -*-
"""Dictionaries

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1I8kxzEMJcWNeBnMZUMBwXGA5VCxKRoMi
"""

#1:
dic = { }

while True :
    product = input("Enter the name of product (enter q for quit ): ")
    if product == "q":
        print()
        break
    else:
        price = int(input("Enter the price of product : "))
        dic [ product ] = price

while True :
    name = input("Enter the name of product those you have entered (enter q for quit ): ")
    if name == "q":
        break
    else :
        if name not in dic :
            print("Name of product is invalid")
            print()
        else :
            print("Price of product : ",dic[name])
            print()

#3:
#a
month = { "jan" : 31 , "feb" : 28 , "march" : 31 , "april" : 30 , "may" : 31 , "june" : 30 , "july" : 31 , "aug" : 31 , "sept" : 30 , "oct" : 31 , "nov" : 30 , "dec" : 31}

user_month = input("Enter the month name in short form : ")
print("Number of days in ",user_month,"=",month [ user_month ])

#b
month = { "jan" : 31 , "feb" : 28 , "march" : 31 , "april" : 30 , "may" : 31 , "june" : 30 , "july" : 31 , "aug" : 31 , "sept" : 30 , "oct" : 31 , "nov" : 30 , "dec" : 31}

list2 = list ( month . keys() )
list2.sort()
print(list2)

#c
month = { "jan" : 31 , "feb" : 28 , "march" : 31 , "april" : 30 , "may" : 31 , "june" : 30 , "july" : 31 , "aug" : 31 , "sept" : 30 , "oct" : 31 , "nov" : 30 , "dec" : 31}

print( "Month which have 31 days!")
for i in month :
    if month [ i ] == 31 :
        print( i )

#d
month = { "jan" : 31 , "feb" : 28 , "march" : 31 , "april" : 30 , "may" : 31 , "june" : 30 , "july" : 31 , "aug" : 31 , "sept" : 30 , "oct" : 31 , "nov" : 30 , "dec" : 31}

print("Month according to number of days")
print("feb")
for i in month :
    if month [ i ] == 30 :
        print(i)
for i in month :
    if month [ i ] == 31 :
        print(i)

#4:
dic = {'Abdul' : "2003",'Rafay' : "1809",'Amir' : "1912",'Ahmed' : "2003",'Bilal' : "9834",'Chughtai' : "1990",'Muhammad' : "2001",'Ibraheem' : "1996",'Lughmani' : "1998",'Lab' : "1999" }

username = input("Enter username :- ")

if username in dic :
    password = input("Enter password :- ")
    if dic[username] == password :
        print ("You are now logged into the system.")
    else :
        print ("Invalid password.")
else :
    print ("You are not valid user.")

#6
dic ={}
list1 = []
list2 = []
while True :
    name = input ("Enter the name of team (enter q for quit)= ")
    if name == "q" :
        print()
        break
    else :
        win = int (input("Enter the no.of win match = "))
        loss = int(input("Enter the no.of loss match = "))
        print()
        dic [ name ] = [ win , loss ]
        list1 += [ win ]
        if win > 0 :
            list2 += [ name ]

nam = input ("Enter the name of team For Winning = ")
print ("Winning percentage = ",dic [ nam ][0] *100 / (dic [nam ][0] + dic[nam ][1] ))
print()
print("Winning list of all team = ",list1)
print("Team who has winning records are ",list2)